# Generated by Django 5.0.6 on 2024-06-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_course',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
