# Generated by Django 5.0.6 on 2024-06-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_price_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public_date',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='course',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
