# Generated by Django 5.0.6 on 2024-06-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_url',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сессия для оплаты в Stripe'),
        ),
    ]
