# Generated by Django 5.0.6 on 2024-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_payment_pay_url_payment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_url',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сессия для оплаты в Stripe'),
        ),
    ]
